/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/


-- Find total customers by countries
SELECT
country,
COUNT(customer_id) AS [total number of customers]
FROM gold.dim_customers
GROUP BY country

-- Find total customers by gender
SELECT
	gender,
	COUNT(customer_id) AS number_if_customers
FROM gold.dim_customers
GROUP BY gender

-- Find total products by category
SELECT
category,
COUNT(product_id) AS [number of items in this category]
FROM gold.dim_products
GROUP BY category
ORDER BY category DESC

-- What is the average costs in each category?
SELECT
category,
AVG(cost) AS [avg cost]
FROM gold.dim_products
GROUP BY category
ORDER BY AVG(cost) DESC

-- What is the total revenue generated for each category?
SELECT 
p.category,
SUM(s.sales_amount) AS revenue
FROM gold.dim_products AS p
LEFT JOIN gold.fact_sales AS s
ON s.product_key = p.product_key
WHERE category IS NOT NULL
GROUP BY category
ORDER BY SUM(s.sales_amount) DESC


-- What is the total revenue generated by each customer?

SELECT 
c.customer_id,
c.first_name,
c.last_name,
SUM(s.sales_amount) AS revenue
FROM gold.dim_customers AS c
LEFT JOIN gold.fact_sales AS s
ON s.customer_key = c.customer_key
GROUP BY c.customer_id,
c.first_name,
c.last_name
ORDER BY SUM(s.sales_amount) DESC

-- What is the distribution of sold items across countries?
SELECT 
c.country,
SUM(s.quantity) AS [number of sold items]
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = s.customer_key
GROUP BY country
ORDER BY SUM(s.quantity) DESC

